### ISSUE TITLE
Picked up frog leg from quark then crash... 1.12.2

### ISSUE THREAD

**Issue by Sageking10** [Vazkii/AutoRegLib#33]
I Used the AutoRegLib-1.3-31 version on the latest version of quark and the latest version of forge (1.12.2 - 14.23.5.2838). I Killed a Frog and picked up its leg. Shortly after the game crashed and gave me this. https://paste.dimdev.org/okiwefajoy.mccrash
EDIT: apparently, this crash happens when a mob drops something with this mob installed.

**Comment by Johni0702** [comment]
@yrsegal 
This seems more like a workaround than a fix.
Why is the Runnable `null` in the first place? Is that expected behavior?
It looks like to me that passing `null` to `addAction` can never serve any purpose. So having `addAction` throw a NPE and then fixing the caller sounds like a better solution.

**Comment by yrsegal** [comment]
As for why it's that way, don't ask me. Vazkii did it.
